### ISSUE TITLE
install on VPS ubuntu

### ISSUE THREAD

**Issue by ingnelson** [shpaker/soxyproxy#5]
Hello sir.
I want to use the soxyproxy on my VPS . can you tell me what command should i write ?
i install python3, i clone your repo, i install screen .
can you give a mini tutorial , please where to add the listen port .
by the way i want to use windows as a client using python for windows.

i will wait your answer.

**Comment by shpaker** [comment]
Hi, @ingnelson.

I don't think this project is ready for real usage. From the beginning it was implemented for study purposes. But, if you want to try it, you can execute service with docker:

Create file `.htpasswd ` with authorization credentials https://pypi.org/project/pypiserver/#apache-like-authentication-htpasswd

```shell
docker run -v ./.htpasswd:/.htpasswd ghcr.io/shpaker/soxyproxy socks5 --port 443 --passwords /.htpasswd
```

Or you can run script directly after installation from pypi:

```shell
pip install soxyproxy -U
```

And then execute:

```shell
soxyproxy socks5 --port 443 --passwords .htpasswd
```
